- name: Start Workflow Execution
  action: start
  inputs:
    context: WorkflowContext
    input: any
    workflow_id: string #required
  outputs:
    execution_id: string
    status: string
    success: boolean

- name: Pause Workflow Execution
  action: pause
  inputs:
    execution_id: string #required
    reason: string
  outputs:
    success: boolean

- name: Resume Paused Workflow
  action: resume
  inputs:
    execution_id: string #required
    input: any
  outputs:
    success: boolean

- name: Cancel Workflow Execution
  action: cancel
  inputs:
    execution_id: string #required
    reason: string
  outputs:
    success: boolean

- name: Get Workflow Status
  action: get_status
  inputs:
    execution_id: string #required
  outputs:
    completed_at: datetime
    current_step: string
    error: string
    progress: float
    started_at: datetime
    status: pending | running | paused | completed | failed | cancelled

- name: Get Workflow Result
  action: get_result
  inputs:
    execution_id: string #required
  outputs:
    completed: boolean
    error: string
    output: any

- name: List Workflow Executions
  action: list_executions
  inputs:
    end_date: datetime
    limit: integer = 100
    offset: integer = 0
    start_date: datetime
    status: string
    workflow_id: string
  outputs:
    executions: list[WorkflowExecutionInfo]
    total: integer

- name: Send Signal To Workflow
  action: signal
  inputs:
    execution_id: string #required
    payload: any
    signal_name: string #required
  outputs:
    success: boolean

- name: Wait For External Event
  action: wait_for_event
  inputs:
    event_name: string #required
    execution_id: string #required
    timeout: integer = 3600
  outputs:
    payload: any
    received: boolean
    timed_out: boolean

- name: Get Workflow History
  action: history
  inputs:
    execution_id: string #required
  outputs:
    events: list[WorkflowHistoryEvent]
    total: integer

- name: Retry Failed Step
  action: retry_step
  inputs:
    execution_id: string #required
    step_id: string #required
  outputs:
    success: boolean

- name: Skip Workflow Step
  action: skip_step
  inputs:
    execution_id: string #required
    output: any
    step_id: string #required
  outputs:
    success: boolean

- name: Terminate All Executions
  action: terminate_all
  inputs:
    reason: string
    workflow_id: string #required
  outputs:
    success: boolean
    terminated_count: integer

- name: WorkflowExecution
  class:
    execution_id: string
    workflow_id: string
    status: string
    current_step: string
    input: any
    output: any
    started_at: datetime
    completed_at: datetime
    error: string

- name: WorkflowContext
  class:
    values: map[string, any]

- name: WorkflowExecutionInfo
  class:
    execution_id: string
    workflow_id: string
    status: string
    started_at: datetime
    completed_at: datetime

- name: WorkflowHistoryEvent
  class:
    event_id: string
    event_type: string
    step_id: string
    timestamp: datetime
    data: any
