- name: create_function
  inputs:
    architectures: list[x86_64 | arm64]
    code: function_code #required
    code_signing_config_arn: string
    dead_letter_config: dead_letter_config
    description: string
    environment: environment
    ephemeral_storage: ephemeral_storage
    file_system_configs: list[file_system_config]
    function_name: string #required
    handler: string
    image_config: image_config
    kms_key_arn: string
    layers: list[string]
    logging_config: logging_config
    memory_size: int = 128
    package_type: zip | image = zip
    publish: boolean = false
    region: string
    role: string #required
    runtime: string
    snap_start: snap_start
    tags: lambda_tags
    timeout: int = 3
    tracing_config: tracing_config
    vpc_config: vpc_config
  outputs:
    architectures: list[string]
    code_sha256: string
    code_size: int
    dead_letter_config: dead_letter_config
    description: string
    environment: environment
    ephemeral_storage: ephemeral_storage
    file_system_configs: list[file_system_config]
    function_arn: string
    function_name: string
    handler: string
    image_config_response: image_config_response
    kms_key_arn: string
    last_modified: string
    last_update_status: string
    layers: list[layer]
    logging_config: logging_config
    master_arn: string
    memory_size: int
    package_type: string
    revision_id: string
    role: string
    runtime: string
    signing_job_arn: string
    signing_profile_version_arn: string
    snap_start: snap_start_response
    state: string
    state_reason: string
    state_reason_code: string
    success: boolean
    timeout: int
    tracing_config: tracing_config_response
    version: string
    vpc_config: vpc_config_response

- name: delete_function
  inputs:
    function_name: string #required
    qualifier: string
    region: string
  outputs:
    success: boolean

- name: get_function
  inputs:
    function_name: string #required
    qualifier: string
    region: string
  outputs:
    code: function_code_location
    concurrency: concurrency
    configuration: function_configuration
    tags: lambda_tags

- name: list_functions
  inputs:
    function_version: all
    marker: string
    master_region: string
    max_items: int = 50
    region: string
  outputs:
    functions: list[function_configuration]
    next_marker: string

- name: update_function_code
  inputs:
    architectures: list[x86_64 | arm64]
    dry_run: boolean = false
    function_name: string #required
    image_uri: string
    publish: boolean = false
    region: string
    revision_id: string
    s3_bucket: string
    s3_key: string
    s3_object_version: string
    zip_file: bytes
  outputs:
    architectures: list[string]
    code_sha256: string
    code_size: int
    function_arn: string
    function_name: string
    handler: string
    last_modified: string
    last_update_status: string
    last_update_status_reason: string
    last_update_status_reason_code: string
    revision_id: string
    runtime: string
    state: string
    state_reason: string
    state_reason_code: string
    success: boolean
    version: string

- name: update_function_configuration
  inputs:
    dead_letter_config: dead_letter_config
    description: string
    environment: environment
    ephemeral_storage: ephemeral_storage
    file_system_configs: list[file_system_config]
    function_name: string #required
    handler: string
    image_config: image_config
    kms_key_arn: string
    layers: list[string]
    logging_config: logging_config
    memory_size: int
    region: string
    revision_id: string
    role: string
    runtime: string
    snap_start: snap_start
    timeout: int
    tracing_config: tracing_config
    vpc_config: vpc_config
  outputs:
    architectures: list[string]
    code_sha256: string
    code_size: int
    dead_letter_config: dead_letter_config
    description: string
    environment: environment
    ephemeral_storage: ephemeral_storage
    file_system_configs: list[file_system_config]
    function_arn: string
    function_name: string
    handler: string
    image_config_response: image_config_response
    kms_key_arn: string
    last_modified: string
    last_update_status: string
    layers: list[layer]
    logging_config: logging_config
    memory_size: int
    package_type: string
    revision_id: string
    role: string
    runtime: string
    snap_start: snap_start_response
    state: string
    state_reason: string
    state_reason_code: string
    success: boolean
    timeout: int
    tracing_config: tracing_config_response
    version: string
    vpc_config: vpc_config_response

- name: invoke
  inputs:
    client_context: string
    function_name: string #required
    invocation_type: request_response | event | dry_run = request_response
    log_type: none | tail = none
    payload: bytes
    qualifier: string
    region: string
  outputs:
    executed_version: string
    function_error: string
    log_result: string
    payload: bytes
    status_code: int
    success: boolean

- name: invoke_async
  inputs:
    function_name: string #required
    invoke_args: bytes #required
    region: string
  outputs:
    status: int
    success: boolean

- name: publish_version
  inputs:
    code_sha256: string
    description: string
    function_name: string #required
    region: string
    revision_id: string
  outputs:
    architectures: list[string]
    code_sha256: string
    code_size: int
    description: string
    function_arn: string
    function_name: string
    handler: string
    last_modified: string
    memory_size: int
    package_type: string
    revision_id: string
    role: string
    runtime: string
    state: string
    state_reason: string
    state_reason_code: string
    success: boolean
    timeout: int
    version: string

- name: list_versions_by_function
  inputs:
    function_name: string #required
    marker: string
    max_items: int = 50
    region: string
  outputs:
    next_marker: string
    versions: list[function_configuration]

- name: create_alias
  inputs:
    description: string
    function_name: string #required
    function_version: string #required
    name: string #required
    region: string
    routing_config: alias_routing_configuration
  outputs:
    alias_arn: string
    description: string
    function_version: string
    name: string
    revision_id: string
    routing_config: alias_routing_configuration
    success: boolean

- name: delete_alias
  inputs:
    function_name: string #required
    name: string #required
    region: string
  outputs:
    success: boolean

- name: get_alias
  inputs:
    function_name: string #required
    name: string #required
    region: string
  outputs:
    alias_arn: string
    description: string
    function_version: string
    name: string
    revision_id: string
    routing_config: alias_routing_configuration

- name: list_aliases
  inputs:
    function_name: string #required
    function_version: string
    marker: string
    max_items: int = 50
    region: string
  outputs:
    aliases: list[alias_configuration]
    next_marker: string

- name: update_alias
  inputs:
    description: string
    function_name: string #required
    function_version: string
    name: string #required
    region: string
    revision_id: string
    routing_config: alias_routing_configuration
  outputs:
    alias_arn: string
    description: string
    function_version: string
    name: string
    revision_id: string
    routing_config: alias_routing_configuration
    success: boolean

- name: create_event_source_mapping
  inputs:
    amazon_managed_kafka_event_source_config: amazon_managed_kafka_event_source_config
    batch_size: int
    bisect_batch_on_function_error: boolean
    destination_config: destination_config
    document_db_event_source_config: document_db_event_source_config
    enabled: boolean = true
    event_source_arn: string
    filter_criteria: filter_criteria
    function_name: string #required
    function_response_types: list[report_batch_item_failures]
    maximum_batching_window_in_seconds: int
    maximum_record_age_in_seconds: int
    maximum_retry_attempts: int
    parallelization_factor: int
    queues: list[string]
    region: string
    scaling_config: scaling_config
    self_managed_event_source: self_managed_event_source
    self_managed_kafka_event_source_config: self_managed_kafka_event_source_config
    source_access_configurations: list[source_access_configuration]
    starting_position: TRIM_HORIZON | latest | AT_TIMESTAMP
    starting_position_timestamp: date
    topics: list[string]
    tumbling_window_in_seconds: int
  outputs:
    amazon_managed_kafka_event_source_config: amazon_managed_kafka_event_source_config
    batch_size: int
    bisect_batch_on_function_error: boolean
    destination_config: destination_config
    document_db_event_source_config: document_db_event_source_config
    event_source_arn: string
    filter_criteria: filter_criteria
    function_arn: string
    function_response_types: list[string]
    last_modified: date
    last_processing_result: string
    maximum_batching_window_in_seconds: int
    maximum_record_age_in_seconds: int
    maximum_retry_attempts: int
    parallelization_factor: int
    queues: list[string]
    scaling_config: scaling_config
    self_managed_event_source: self_managed_event_source
    self_managed_kafka_event_source_config: self_managed_kafka_event_source_config
    source_access_configurations: list[source_access_configuration]
    starting_position: string
    starting_position_timestamp: date
    state: string
    state_transition_reason: string
    success: boolean
    topics: list[string]
    tumbling_window_in_seconds: int
    uuid: string

- name: delete_event_source_mapping
  inputs:
    region: string
    uuid: string #required
  outputs:
    event_source_arn: string
    function_arn: string
    state: string
    success: boolean
    uuid: string

- name: get_event_source_mapping
  inputs:
    region: string
    uuid: string #required
  outputs:
    amazon_managed_kafka_event_source_config: amazon_managed_kafka_event_source_config
    batch_size: int
    bisect_batch_on_function_error: boolean
    destination_config: destination_config
    event_source_arn: string
    filter_criteria: filter_criteria
    function_arn: string
    last_modified: date
    last_processing_result: string
    maximum_batching_window_in_seconds: int
    maximum_record_age_in_seconds: int
    maximum_retry_attempts: int
    parallelization_factor: int
    queues: list[string]
    scaling_config: scaling_config
    self_managed_event_source: self_managed_event_source
    source_access_configurations: list[source_access_configuration]
    starting_position: string
    state: string
    state_transition_reason: string
    topics: list[string]
    tumbling_window_in_seconds: int
    uuid: string

- name: list_event_source_mappings
  inputs:
    event_source_arn: string
    function_name: string
    marker: string
    max_items: int = 100
    region: string
  outputs:
    event_source_mappings: list[event_source_mapping_configuration]
    next_marker: string

- name: update_event_source_mapping
  inputs:
    batch_size: int
    bisect_batch_on_function_error: boolean
    destination_config: destination_config
    document_db_event_source_config: document_db_event_source_config
    enabled: boolean
    filter_criteria: filter_criteria
    function_name: string
    function_response_types: list[report_batch_item_failures]
    maximum_batching_window_in_seconds: int
    maximum_record_age_in_seconds: int
    maximum_retry_attempts: int
    parallelization_factor: int
    region: string
    scaling_config: scaling_config
    source_access_configurations: list[source_access_configuration]
    tumbling_window_in_seconds: int
    uuid: string #required
  outputs:
    batch_size: int
    bisect_batch_on_function_error: boolean
    destination_config: destination_config
    event_source_arn: string
    filter_criteria: filter_criteria
    function_arn: string
    last_modified: date
    maximum_batching_window_in_seconds: int
    maximum_record_age_in_seconds: int
    maximum_retry_attempts: int
    parallelization_factor: int
    scaling_config: scaling_config
    source_access_configurations: list[source_access_configuration]
    state: string
    state_transition_reason: string
    success: boolean
    tumbling_window_in_seconds: int
    uuid: string

- name: add_permission
  inputs:
    method: string #required
    event_source_token: string
    function_name: string #required
    function_url_auth_type: none | AWS_IAM
    principal: string #required
    principal_org_id: string
    qualifier: string
    region: string
    revision_id: string
    source_account: string
    source_arn: string
    statement_id: string #required
  outputs:
    statement: string
    success: boolean

- name: remove_permission
  inputs:
    function_name: string #required
    qualifier: string
    region: string
    revision_id: string
    statement_id: string #required
  outputs:
    success: boolean

- name: get_policy
  inputs:
    function_name: string #required
    qualifier: string
    region: string
  outputs:
    policy: string
    revision_id: string

- name: create_function_url_config
  inputs:
    auth_type: none | AWS_IAM #required
    cors: cors
    function_name: string #required
    invoke_mode: buffered | RESPONSE_STREAM = buffered
    qualifier: string
    region: string
  outputs:
    auth_type: string
    cors: cors
    creation_time: string
    function_arn: string
    function_url: string
    invoke_mode: string
    success: boolean

- name: delete_function_url_config
  inputs:
    function_name: string #required
    qualifier: string
    region: string
  outputs:
    success: boolean

- name: get_function_url_config
  inputs:
    function_name: string #required
    qualifier: string
    region: string
  outputs:
    auth_type: string
    cors: cors
    creation_time: string
    function_arn: string
    function_url: string
    invoke_mode: string
    last_modified_time: string

- name: update_function_url_config
  inputs:
    auth_type: none | AWS_IAM
    cors: cors
    function_name: string #required
    invoke_mode: buffered | RESPONSE_STREAM
    qualifier: string
    region: string
  outputs:
    auth_type: string
    cors: cors
    creation_time: string
    function_arn: string
    function_url: string
    invoke_mode: string
    last_modified_time: string
    success: boolean

- name: list_function_url_configs
  inputs:
    function_name: string #required
    marker: string
    max_items: int = 50
    region: string
  outputs:
    function_url_configs: list[function_url_config]
    next_marker: string

- name: put_function_concurrency
  inputs:
    function_name: string #required
    region: string
    reserved_concurrent_executions: int #required
  outputs:
    reserved_concurrent_executions: int
    success: boolean

- name: delete_function_concurrency
  inputs:
    function_name: string #required
    region: string
  outputs:
    success: boolean

- name: get_function_concurrency
  inputs:
    function_name: string #required
    region: string
  outputs:
    reserved_concurrent_executions: int

- name: put_provisioned_concurrency_config
  inputs:
    function_name: string #required
    provisioned_concurrent_executions: int #required
    qualifier: string #required
    region: string
  outputs:
    allocated_provisioned_concurrent_executions: int
    available_provisioned_concurrent_executions: int
    last_modified: string
    requested_provisioned_concurrent_executions: int
    status: string
    status_reason: string
    success: boolean

- name: delete_provisioned_concurrency_config
  inputs:
    function_name: string #required
    qualifier: string #required
    region: string
  outputs:
    success: boolean

- name: get_provisioned_concurrency_config
  inputs:
    function_name: string #required
    qualifier: string #required
    region: string
  outputs:
    allocated_provisioned_concurrent_executions: int
    available_provisioned_concurrent_executions: int
    last_modified: string
    requested_provisioned_concurrent_executions: int
    status: string
    status_reason: string

- name: list_provisioned_concurrency_configs
  inputs:
    function_name: string #required
    marker: string
    max_items: int = 50
    region: string
  outputs:
    next_marker: string
    provisioned_concurrency_configs: list[provisioned_concurrency_config_list_item]

- name: publish_layer_version
  inputs:
    compatible_architectures: list[x86_64 | arm64]
    compatible_runtimes: list[string]
    content: layer_version_content_input #required
    description: string
    layer_name: string #required
    license_info: string
    region: string
  outputs:
    compatible_architectures: list[string]
    compatible_runtimes: list[string]
    content: layer_version_content_output
    created_date: string
    description: string
    layer_arn: string
    layer_version_arn: string
    license_info: string
    success: boolean
    version: int

- name: delete_layer_version
  inputs:
    layer_name: string #required
    region: string
    version_number: int #required
  outputs:
    success: boolean

- name: get_layer_version
  inputs:
    layer_name: string #required
    region: string
    version_number: int #required
  outputs:
    compatible_architectures: list[string]
    compatible_runtimes: list[string]
    content: layer_version_content_output
    created_date: string
    description: string
    layer_arn: string
    layer_version_arn: string
    license_info: string
    version: int

- name: list_layers
  inputs:
    compatible_architecture: x8664 | arm64
    compatible_runtime: string
    marker: string
    max_items: int = 50
    region: string
  outputs:
    layers: list[layers_list_item]
    next_marker: string

- name: list_layer_versions
  inputs:
    compatible_architecture: x8664 | arm64
    compatible_runtime: string
    layer_name: string #required
    marker: string
    max_items: int = 50
    region: string
  outputs:
    layer_versions: list[layer_versions_list_item]
    next_marker: string

- name: add_layer_version_permission
  inputs:
    method: string #required
    layer_name: string #required
    organization_id: string
    principal: string #required
    region: string
    revision_id: string
    statement_id: string #required
    version_number: int #required
  outputs:
    revision_id: string
    statement: string
    success: boolean

- name: remove_layer_version_permission
  inputs:
    layer_name: string #required
    region: string
    revision_id: string
    statement_id: string #required
    version_number: int #required
  outputs:
    success: boolean

- name: get_layer_version_policy
  inputs:
    layer_name: string #required
    region: string
    version_number: int #required
  outputs:
    policy: string
    revision_id: string

- name: tag_resource
  inputs:
    region: string
    resource: string #required
    tags: lambda_tags #required
  outputs:
    success: boolean

- name: untag_resource
  inputs:
    region: string
    resource: string #required
    tag_keys: list[string] #required
  outputs:
    success: boolean

- name: list_tags
  inputs:
    region: string
    resource: string #required
  outputs:
    tags: lambda_tags
