- name: Execute Tasks In Parallel
  action: all
  inputs:
    fail_fast: Boolean = true
    max_concurrency: Int
    tasks: List[ParallelTask] #required
    timeout: Int
  outputs:
    completed: Int
    failed: Int
    results: List[ParallelResult]
    success: Boolean

- name: Execute First Successful Task
  action: race
  inputs:
    tasks: List[ParallelTask] #required
    timeout: Int
  outputs:
    result: Any
    success: Boolean
    winner_index: Int

- name: Execute Any Successful Task
  action: Any
  inputs:
    tasks: List[ParallelTask] #required
    timeout: Int
  outputs:
    result: Any
    success: Boolean
    success_index: Int

- name: Execute All And Settle
  action: all_settled
  inputs:
    max_concurrency: Int
    tasks: List[ParallelTask] #required
    timeout: Int
  outputs:
    fulfilled: Int
    rejected: Int
    results: List[ParallelSettledResult]

- name: Map Items In Parallel
  action: Map
  inputs:
    handler: String #required
    items: List[any] #required
    max_concurrency: Int = 10
  outputs:
    errors: List[ParallelError]
    results: List[any]
    success: Boolean

- name: Filter Items In Parallel
  action: filter
  inputs:
    handler: String #required
    items: List[any] #required
    max_concurrency: Int = 10
  outputs:
    count: Int
    results: List[any]

- name: Reduce Items In Parallel
  action: reduce
  inputs:
    handler: String #required
    initial_value: Any
    items: List[any] #required
    max_concurrency: Int = 10
  outputs:
    result: Any

- name: Execute With Retry
  action: retry
  inputs:
    backoff_multiplier: Float = 2.0
    delay_ms: Int = 1000
    max_attempts: Int = 3
    task: ParallelTask #required
  outputs:
    attempts: Int
    result: Any
    success: Boolean

- name: Execute With Timeout
  action: timeout
  inputs:
    task: ParallelTask #required
    timeout_ms: Int #required
  outputs:
    result: Any
    success: Boolean
    timed_out: Boolean

- name: Execute In Batches
  action: batch
  inputs:
    batch_size: Int = 10
    handler: String #required
    items: List[any] #required
    max_concurrency: Int = 1
  outputs:
    batch_count: Int
    results: List[any]
    success: Boolean

- name: Execute With Semaphore
  action: semaphore
  inputs:
    max_concurrent: Int #required
    tasks: List[ParallelTask] #required
  outputs:
    completed: Int
    failed: Int
    results: List[ParallelResult]

- name: ParallelTask
  class:
    id: String
    handler: String
    input: Any
    timeout: Int

- name: ParallelResult
  class:
    task_id: String
    success: Boolean
    result: Any
    error: String
    duration_ms: Int

- name: ParallelSettledResult
  class:
    task_id: String
    status: Fulfilled | Rejected
    value: Any
    reason: String
    duration_ms: Int

- name: ParallelError
  class:
    task_id: String
    index: Int
    message: String
    code: String
