- name: Start Workflow Execution
  action: start
  inputs:
    context: WorkflowContext
    input: Any
    workflow_id: String #required
  outputs:
    execution_id: String
    status: String
    success: Boolean

- name: Pause Workflow Execution
  action: pause
  inputs:
    execution_id: String #required
    reason: String
  outputs:
    success: Boolean

- name: Resume Paused Workflow
  action: resume
  inputs:
    execution_id: String #required
    input: Any
  outputs:
    success: Boolean

- name: Cancel Workflow Execution
  action: cancel
  inputs:
    execution_id: String #required
    reason: String
  outputs:
    success: Boolean

- name: Get Workflow Status
  action: get_status
  inputs:
    execution_id: String #required
  outputs:
    completed_at: Date
    current_step: String
    error: String
    progress: Float
    started_at: Date
    status: Pending | Running | Paused | Completed | Failed | Cancelled

- name: Get Workflow Result
  action: get_result
  inputs:
    execution_id: String #required
  outputs:
    completed: Boolean
    error: String
    output: Any

- name: List Workflow Executions
  action: list_executions
  inputs:
    end_date: Date
    limit: Int = 100
    offset: Int = 0
    start_date: Date
    status: String
    workflow_id: String
  outputs:
    executions: List[WorkflowExecutionInfo]
    total: Int

- name: Send Signal To Workflow
  action: signal
  inputs:
    execution_id: String #required
    payload: Any
    signal_name: String #required
  outputs:
    success: Boolean

- name: Wait For External Event
  action: wait_for_event
  inputs:
    event_name: String #required
    execution_id: String #required
    timeout: Int = 3600
  outputs:
    payload: Any
    received: Boolean
    timed_out: Boolean

- name: Get Workflow History
  action: history
  inputs:
    execution_id: String #required
  outputs:
    events: List[WorkflowHistoryEvent]
    total: Int

- name: Retry Failed Step
  action: retry_step
  inputs:
    execution_id: String #required
    step_id: String #required
  outputs:
    success: Boolean

- name: Skip Workflow Step
  action: skip_step
  inputs:
    execution_id: String #required
    output: Any
    step_id: String #required
  outputs:
    success: Boolean

- name: Terminate All Executions
  action: terminate_all
  inputs:
    reason: String
    workflow_id: String #required
  outputs:
    success: Boolean
    terminated_count: Int

- name: WorkflowExecution
  class:
    execution_id: String
    workflow_id: String
    status: String
    current_step: String
    input: Any
    output: Any
    started_at: Date
    completed_at: Date
    error: String

- name: WorkflowContext
  class:
    values: Map[String, Any]

- name: WorkflowExecutionInfo
  class:
    execution_id: String
    workflow_id: String
    status: String
    started_at: Date
    completed_at: Date

- name: WorkflowHistoryEvent
  class:
    event_id: String
    event_type: String
    step_id: String
    timestamp: Date
    data: Any
