- action: all
  inputs:
    fail_fast: boolean = true
    max_concurrency: int
    tasks: list[parallel_task] #required
    timeout: int
  outputs:
    completed: int
    failed: int
    results: list[parallel_result]
    success: boolean

- action: race
  inputs:
    tasks: list[parallel_task] #required
    timeout: int
  outputs:
    result: any
    success: boolean
    winner_index: int

- action: any
  inputs:
    tasks: list[parallel_task] #required
    timeout: int
  outputs:
    result: any
    success: boolean
    success_index: int

- action: all_settled
  inputs:
    max_concurrency: int
    tasks: list[parallel_task] #required
    timeout: int
  outputs:
    fulfilled: int
    rejected: int
    results: list[parallel_settled_result]

- action: map
  inputs:
    handler: string #required
    items: list[any] #required
    max_concurrency: int = 10
  outputs:
    errors: list[parallel_error]
    results: list[any]
    success: boolean

- action: filter
  inputs:
    handler: string #required
    items: list[any] #required
    max_concurrency: int = 10
  outputs:
    count: int
    results: list[any]

- action: reduce
  inputs:
    handler: string #required
    initial_value: any
    items: list[any] #required
    max_concurrency: int = 10
  outputs:
    result: any

- action: retry
  inputs:
    backoff_multiplier: float = 2.0
    delay_ms: int = 1000
    max_attempts: int = 3
    task: parallel_task #required
  outputs:
    attempts: int
    result: any
    success: boolean

- action: timeout
  inputs:
    task: parallel_task #required
    timeout_ms: int #required
  outputs:
    result: any
    success: boolean
    timed_out: boolean

- action: batch
  inputs:
    batch_size: int = 10
    handler: string #required
    items: list[any] #required
    max_concurrency: int = 1
  outputs:
    batch_count: int
    results: list[any]
    success: boolean

- action: semaphore
  inputs:
    max_concurrent: int #required
    tasks: list[parallel_task] #required
  outputs:
    completed: int
    failed: int
    results: list[parallel_result]

- object: parallel_task
  class:
    id: string
    handler: string
    input: any
    timeout: int

- object: parallel_result
  class:
    task_id: string
    success: boolean
    result: any
    error: string
    duration_ms: int

- object: parallel_settled_result
  class:
    task_id: string
    status: fulfilled | rejected
    value: any
    reason: string
    duration_ms: int

- object: parallel_error
  class:
    task_id: string
    index: int
    message: string
    code: string
