- name: start
  inputs:
    context: workflow_context
    input: any
    workflow_id: string #required
  outputs:
    execution_id: string
    status: string
    success: boolean

- name: pause
  inputs:
    execution_id: string #required
    reason: string
  outputs:
    success: boolean

- name: resume
  inputs:
    execution_id: string #required
    input: any
  outputs:
    success: boolean

- name: cancel
  inputs:
    execution_id: string #required
    reason: string
  outputs:
    success: boolean

- name: get_status
  inputs:
    execution_id: string #required
  outputs:
    completed_at: date
    current_step: string
    error: string
    progress: float
    started_at: date
    status: pending | running | paused | completed | failed | cancelled

- name: get_result
  inputs:
    execution_id: string #required
  outputs:
    completed: boolean
    error: string
    output: any

- name: list_executions
  inputs:
    end_date: date
    limit: int = 100
    offset: int = 0
    start_date: date
    status: string
    workflow_id: string
  outputs:
    executions: list[workflow_execution_info]
    total: int

- name: signal
  inputs:
    execution_id: string #required
    payload: any
    signal_name: string #required
  outputs:
    success: boolean

- name: wait_for_event
  inputs:
    event_name: string #required
    execution_id: string #required
    timeout: int = 3600
  outputs:
    payload: any
    received: boolean
    timed_out: boolean

- name: history
  inputs:
    execution_id: string #required
  outputs:
    events: list[workflow_history_event]
    total: int

- name: retry_step
  inputs:
    execution_id: string #required
    step_id: string #required
  outputs:
    success: boolean

- name: skip_step
  inputs:
    execution_id: string #required
    output: any
    step_id: string #required
  outputs:
    success: boolean

- name: terminate_all
  inputs:
    reason: string
    workflow_id: string #required
  outputs:
    success: boolean
    terminated_count: int

- name: workflow_execution
  class:
    execution_id: string
    workflow_id: string
    status: string
    current_step: string
    input: any
    output: any
    started_at: date
    completed_at: date
    error: string

- name: workflow_context
  class:
    values: map[string, any]

- name: workflow_execution_info
  class:
    execution_id: string
    workflow_id: string
    status: string
    started_at: date
    completed_at: date

- name: workflow_history_event
  class:
    event_id: string
    event_type: string
    step_id: string
    timestamp: date
    data: any
