use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Validator {
    After { field: String },
    AllowedMimeTypes { types: Vec<String> },
    Alpha,
    Alphanumeric,
    Ascii,
    Base64,
    Before { field: String },
    CascadeDelete,
    Contains { substring: String },
    Country,
    CreditCard,
    Currency,
    Custom { name: String, args: Option<Vec<String>> },
    Date,
    Datetime,
    Deprecated { message: Option<String> },
    Email,
    Encrypted,
    EndsWith { suffix: String },
    Equals { field: String },
    FileExtension { extensions: Vec<String> },
    FilePath,
    Future,
    FutureOrPresent,
    GreaterThan { field: String },
    HasDigit,
    Hashed,
    HasLowercase,
    HasSpecial,
    HasUppercase,
    Hex,
    Iban,
    Immutable,
    Ip,
    Ipv4,
    Ipv6,
    Isbn,
    Json,
    Length { value: i64 },
    LessThan { field: String },
    Locale,
    Lowercase,
    MacAddress,
    Max { value: i64 },
    MaxFileSize { bytes: i64 },
    MaxItems { value: i64 },
    MimeType,
    Min { value: i64 },
    MinItems { value: i64 },
    Negative,
    NoHtml,
    NoneOf { values: Vec<String> },
    NonNegative,
    NonPositive,
    NotBlank,
    NotCommonPassword,
    NotContains { substring: String },
    NotEmpty,
    NotEquals { field: String },
    Numeric,
    OneOf { values: Vec<String> },
    Past,
    PastOrPresent,
    Pattern { regex: String },
    Phone,
    Positive,
    Range { min: i64, max: i64 },
    ReadOnly,
    Redacted,
    Reference { table: String, field: String },
    Required,
    RestrictDelete,
    Semver,
    Sensitive,
    SetNullOnDelete,
    Slug,
    StartsWith { prefix: String },
    Time,
    Timezone,
    Trimmed,
    Unique,
    UniqueItems,
    Uppercase,
    Url,
    Uuid,
    WithinDuration { duration: String },
    WriteOnly,
}
