- event: app_started
  schema:
    app_id: id #required
    app_name: string #required
    version: string #required
    environment: development | staging | production = development
    host: string #required
    port: int #min(1) #max(65535)
    started_at: date = now()

- event: app_stopped
  schema:
    app_id: id #required
    app_name: string #required
    reason: shutdown | crash | restart | sigterm | sigint = shutdown
    exit_code: int? #min(0) #max(255)
    uptime_seconds: int? #min(0)
    stopped_at: date = now()

- event: app_config_updated
  schema:
    app_id: id #required
    config_key: string #required
    old_value: string?
    new_value: string?
    source: file | env | remote | api = file
    updated_by: string?
    updated_at: date = now()

- event: app_config_loaded
  schema:
    app_id: id #required
    config_path: string?
    source: file | env | remote | api = file
    keys_loaded: int? #min(0)
    loaded_at: date = now()

- event: app_health_check
  schema:
    app_id: id #required
    status: healthy | degraded | unhealthy = healthy
    checks_passed: int? #min(0)
    checks_failed: int? #min(0)
    response_time_ms: int? #min(0)
    checked_at: date = now()

- event: app_ready
  schema:
    app_id: id #required
    app_name: string #required
    startup_time_ms: int? #min(0)
    ready_at: date = now()

- event: app_shutting_down
  schema:
    app_id: id #required
    reason: shutdown | restart | sigterm | sigint | timeout = shutdown
    grace_period_ms: int? #min(0)
    initiated_at: date = now()

- event: app_error
  schema:
    app_id: id #required
    error_type: string #required
    error_message: string #required
    stack_trace: string?
    severity: debug | info | warning | error | critical = error
    occurred_at: date = now()

- event: app_connection_pool_created
  schema:
    app_id: id #required
    pool_name: string #required
    pool_type: database | redis | http | custom = database
    min_connections: int? #min(0)
    max_connections: int? #min(1)
    created_at: date = now()

- event: app_connection_pool_exhausted
  schema:
    app_id: id #required
    pool_name: string #required
    active_connections: int #min(0)
    max_connections: int #min(1)
    waiting_requests: int? #min(0)
    occurred_at: date = now()